#ifndef __RDX_CORETYPEATTRIBS_HPP__
#define __RDX_CORETYPEATTRIBS_HPP__

#include "rdx_coretypes.hpp"
#include "rdx_typeprocessor.hpp"

RDX_DECLARE_SIMPLE_NATIVE_STRUCT(rdxUInt8);
RDX_DECLARE_SIMPLE_NATIVE_STRUCT(rdxUInt16);
RDX_DECLARE_SIMPLE_NATIVE_STRUCT(rdxUInt32);
RDX_DECLARE_SIMPLE_NATIVE_STRUCT(rdxUInt64);
RDX_DECLARE_SIMPLE_NATIVE_STRUCT(rdxInt8);
RDX_DECLARE_SIMPLE_NATIVE_STRUCT(rdxInt16);
RDX_DECLARE_SIMPLE_NATIVE_STRUCT(rdxInt32);
RDX_DECLARE_SIMPLE_NATIVE_STRUCT(rdxInt64);
RDX_DECLARE_SIMPLE_NATIVE_STRUCT(rdxFloat32);
RDX_DECLARE_SIMPLE_NATIVE_STRUCT(rdxFloat64);

#ifdef RDX_WCHAR_T_IS_NATIVE
RDX_DECLARE_SIMPLE_NATIVE_STRUCT(wchar_t);
#endif


#endif
