#include "rdx_coretypes.hpp"
#include "rdx_typeprocessordefs.hpp"
#include "rdx_reftypedefs.hpp"
#include "rdx_coretypeattribs.hpp"

RDX_IMPLEMENT_SIMPLE_NATIVE_STRUCT(rdxUInt8);
RDX_IMPLEMENT_SIMPLE_NATIVE_STRUCT(rdxUInt16);
RDX_IMPLEMENT_SIMPLE_NATIVE_STRUCT(rdxUInt32);
RDX_IMPLEMENT_SIMPLE_NATIVE_STRUCT(rdxUInt64);
RDX_IMPLEMENT_SIMPLE_NATIVE_STRUCT(rdxInt8);
RDX_IMPLEMENT_SIMPLE_NATIVE_STRUCT(rdxInt16);
RDX_IMPLEMENT_SIMPLE_NATIVE_STRUCT(rdxInt32);
RDX_IMPLEMENT_SIMPLE_NATIVE_STRUCT(rdxInt64);
RDX_IMPLEMENT_SIMPLE_NATIVE_STRUCT(rdxFloat32);
RDX_IMPLEMENT_SIMPLE_NATIVE_STRUCT(rdxFloat64);

#ifdef RDX_WCHAR_T_IS_NATIVE
RDX_IMPLEMENT_SIMPLE_NATIVE_STRUCT(wchar_t);
#endif
